### ISSUE TITLE
desktop-environment-toggle-mute doesn't work when current buffer is a remote file

### ISSUE THREAD

**Issue by divansantana** [DamienCassou/desktop-environment#16]
Hi

When you are editing say a remote file over tramp and call desktop-environment-toggle-mute function, one gets an error like so:

```
/bin/sh: amixer: command not found
```

Switching to a non-tramp buffer and calling the function again works around the issue.

**Comment by DamienCassou** [comment]
I completely agree with you. Would you like to send a PR?
