### ISSUE TITLE
birghtness managment not working

### ISSUE THREAD

**Issue by MiroYld** [DamienCassou/desktop-environment#34]
Hello, I have an issue on my exwm configuration, I can't change my current brighlight. 
When I try to decrease or increase the brightness of my PC.
I get the message ```new brightness value: 68%``` but this value never changes.
I just add the package with guix and in my config file I do 
```(desktop-environment-mode)```
My configuration is also available at: https://github.com/MiroYld/emacs-conf if you want to try to reproduce the bug

**Comment by DamienCassou** [comment]
Thank you for your issue. Can you please try in a terminal to execute:

```session
$ brightnessctl set 10%+
```

And tell me if it works or not? You can execute it more than once to further increase brightness.

**Comment by MiroYld** [comment]
Hello @DamienCassou 
I confirm to you that indeed from a terminal the commands work correctly only with ```sudo``` prefix
```
➜  ~ sudo brightnessctl set 20%-
Updated device 'intel_backlight':
Device 'intel_backlight' of class 'backlight':
        Current brightness: 111 (28%)
        Max brightness: 400

➜  ~ sudo brightnessctl set 20%+
Updated device 'intel_backlight':
Device 'intel_backlight' of class 'backlight':
        Current brightness: 191 (48%)
        Max brightness: 400
```

**Comment by DamienCassou** [comment]
Then I recommend you to investigate why your current user doesn't have the permission to change the brightness.

I don't think this package can do anything so I'm closing this. Feel free to reopen if you need.
