### ISSUE TITLE
Changing volume in full-screen youtube videos does not work

### ISSUE THREAD

**Issue by arael** [DamienCassou/desktop-environment#35]
When the youtube videos are in full-screen it is not possible to change the volume. 

This happens in both Firefox and Chromium.

The only way to change the volume is to exit the full-screen mode.

There are no errors. Please let me know if you need more info.

I tried both with the latest EXWM and with the stable Elpa version.

**Comment by DamienCassou** [comment]
Hi @arael. I have no idea, I'm sorry. I use neither EXWM nor desktop-environment anymore.
