### ISSUE TITLE
`setq: Symbol’s value as variable is void: counsel-linux-apps-faulty` when running `(app-launcher-run-app)`

### ISSUE THREAD

**Issue by yusi1** [DamienCassou/desktop-environment#36]
Emacs Version: `29.3`
OS: `Linux`
Package Version: `20230903.1229`

**Comment by DamienCassou** [comment]
Can you please explain how to reproduce the issue? I have a hard time understanding the relationship between the error message you get and this package.

**Comment by yusi1** [comment]
> Can you please explain how to reproduce the issue? I have a hard time understanding the relationship between the error message you get and this package.

oh wait, I reported this to the wrong package on Github, this is the correct one: https://github.com/SebastienWae/app-launcher

Sorry
