### ISSUE TITLE
How to enable desktop-environment-mode by default with exwm spacemacs

### ISSUE THREAD

**Issue by RidaAyed** [DamienCassou/desktop-environment#4]
In order to use this very useful package I must enable it first by hitting `M-x desktop-environment-mode`.

How can I enable it permanently?

Enabling the mode with `customize-option` adds this line to `.spacemacs`:

```
'(desktop-environment-mode t nil (desktop-environment))
```

,which returns the error below and stops the startup of exwm.

```
Error loading .spacemacs: (file-missing "Cannot open load file" "No such file or directory" "desktop-environment")
```

I've installed the package with this line in `.spacemacs`
```
   dotspacemacs-additional-packages '(desktop-environment)
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(mermaid elfeed
         (geolocation :variables geolocation-enable-weather-forecast t)
         python prodigy pdf-tools plantuml
         (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/mu4e")
         (colors :variables colors-enable-nyan-cat-progress-bar nil)
         finance exwm
         (ranger :variables ranger-show-preview t)
         helm auto-completion better-defaults emacs-lisp git markdown
         (org :variables org-enable-reveal-js-support t)
         (shell :variables shell-default-height 30 shell-default-position 'right)
         (spell-checking :variables spell-checking-enable-by-default nil)
         syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by DamienCassou** [comment]
Hi @RidaAyed.

I know nothing about Spacemacs so I don't think I will be able to help. This should work:

```emacs
(require 'desktop-environment)
(desktop-environment-mode)
```

**Comment by RidaAyed** [comment]
Hi @DamienCassou 

Indeed. Adding your lines to this section works:
```
(defun dotspacemacs/user-config ())
```
Thank you
